### ISSUE TITLE
Work around too-large LLVM files

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git-sdk-arm64#7]
Latest night's `sync` [failed](https://github.com/git-for-windows/git-sdk-arm64/actions/runs/4586636538/jobs/8099618941#step:5:3523) with one error and two warnings:

```
[...]
+ git push origin refs/heads/main
remote: warning: File clangarm64/bin/llvm-exegesis.exe is 78.99 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File clangarm64/bin/libclang-cpp.dll is 52.36 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: error: Trace: 309641135192764786c9dc4a0d2bbb1accf9f8214e1fc5d81d84470a67062f34        
remote: error: See https://gh.io/lfs for more information.        
remote: error: File clangarm64/bin/libLLVM-16.dll is 103.60 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com./
[...]
```

Unfortunately, there is no way around the 100MB restriction (other than going the Git LFS route).

One possibility to address this that comes to my mind is to store a compressed `libLLVM-16.dll.gz` (it compresses down to 34MB via `gzip-1`) and uncompress it via `/etc/profile.d/<something>` (and add the uncompressed file to `.gitignore`).

/cc @dennisameling

**Comment by dscho** [comment]
> Is Git LFS totally out of the question here?

I'd rather avoid it, TBH.

> it just feels to me that there's too many moving parts involved that might also break in the future. WDYT?

Makes sense. So I looked for a different solution and thought I found something in [UPX](https://upx.github.io/) (which is [available in MSYS2](https://packages.msys2.org/base/upx)). It provides a way to compress `.exe` and `.dll` files such that they are automatically decompressed when they're being loaded.

However, it seems that it does not like the `libLLVM-16.dll` file I threw at it:

```console
$ upx.exe --verbose libLLVM-16.dll
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: libLLVM-16.dll: CantPackException: can't pack new-exe

Packed 0 files.
```

The explanation seems to be here: https://github.com/upx/upx/issues/650 (support for win64/arm64* is labeled as `help-wanted`).

**Comment by dscho** [comment]
@dennisameling maybe `strip libLLVM-16.dll` brings it down to size?

**Comment by dscho** [comment]
> @dennisameling maybe `strip libLLVM-16.dll` brings it down to size?

It does.

Closing via https://github.com/git-for-windows/git-sdk-arm64/commit/4e626dd04e337d3c40b8d86774f5b0a601400e2d and https://github.com/git-for-windows/git-sdk-arm64/actions/runs/4794555349.

**Comment by dscho** [comment]
@dennisameling note: this is but a band aid. The `libLLVM-16.dll` file currently weighs 104MB before stripping, 95MB after. It looks as if it's only a matter of time until even the stripped version will blast through the limit. So I think I'd still like to pursue the UPX route, even if I definitely lack the time to do it on my own. Would you be game for a pairing session where we scope out the "T shirt size" of how big of a project it would be to teach UPX what we need it to do?

**Comment by rimrul** [comment]
> note: this is but a band aid. The `libLLVM-16.dll` file currently weighs 104MB before stripping, 95MB after. It looks as if it's only a matter of time until even the stripped version will blast through the limit. 

I might have started work on a potential longer term solution at
https://github.com/git-for-windows/MINGW-packages/pull/75

MSYS2 builds a pretty versatile `libLLVM` that can be used for a lot of [cross compilation targets](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-clang/PKGBUILD#L226-L232). We could probably build [a smaller `libLLVM`](https://boxbase.org/entries/2018/jun/11/minimal-llvm-build/) that's more focussed towards our needs. But I don't have any reliable numbers yet.

**Comment by rimrul** [comment]
>  I don't have any reliable numbers yet.

I have managed to build an `x86_64` LLVM based on upstreams current 16.0.5. It doesn't package properly, yet, but it did produce numbers.

Upstream as is (downloaded and extracted `mingw-w64-x86_64-llvm-libs-16.05-1-any.tar.zstd`): 107125k
Upstream after `strip libLLVM-16.dll`: 107103k
My small `libLLVM-16.dll` (after the `build` step of `makepkg`) : 94289k
My small `libLLVM-16.dll` after `strip libLLVM-16.dll`: 51829k

**Comment by rimrul** [comment]
And I've got it to package. The binary extracted feom the package is 51853k
